### ISSUE TITLE
[TWB] pdm 模式

### ISSUE THREAD

**Issue by SOVLOOKUP** [QPT-Family/QPT#73]
## Issue类型
建议 or 代码贡献请求

## 我的想法
[pdm](https://github.com/pdm-project/pdm) 是一个 python 包管理器，使项目拥有独立的依赖环境，并有非常清晰的依赖描述，例如:
```toml
[project]
name = "uie-api"
version = "0.0.1"
description = "paddlenlp uie web api"
authors = [
    {name = "sovlookup", email = "gonorth@qq.com"},
]
dependencies = [
    "paddlenlp>=2.3.3",
    "paddlepaddle>=2.3.0",
    "setuptools>=62.6.0",
    "fastapi>=0.78.0",
    "uvicorn[standard]>=0.18.2",
]
requires-python = ">=3.8"
license = {text = "MIT"}
```
一个 pdm 项目示例： https://github.com/SOVLOOKUP/uie-api

## 期待的回应

**希望 qpt 能自动识别 pdm 项目，读取依赖及 python 环境等配置进行打包**
